site:
  title: 'Ferry Landing Suites'
  subtitle: 'Friday Harbor Lodging and Suites'
  description: 'Experience the magic of Ferry Landing Suites, located in the heart of downtown Friday Harbor, mere steps from the ferry.'